### ISSUE TITLE
"Failed to convert objects to paths" on inkscape 1.3

### ISSUE THREAD

**Issue by raboof** [inkcut/inkcut#374]
After updating Inkscape to 1.3, opening a document in inkcut takes a long while, and shows the error message:

```
Failed to convert objects to paths. Continued without converting.
b"terminate called after throwing an instance of 'Gio::Error'\n"
```

The command that is failing is something like:

```
inkscape /tmp/ink_ext_XXXXXX.svgTRX6D2 --actions="select-all;object-unlink-clones;object-to-path" -o /tmp/ink_ext_XXXXXX-prepare.svg
```

However, running this command on the command line works fine. This suggests it might have something to do with running inkscape from the python extension. Even starting it like this works fine though:

```
#!/usr/bin/env python3

from subprocess import Popen, PIPE

file = '/tmp/ink_ext_XXXXXX.svgTRX6D2'
tempfile = '/tmp/ink_ext_XXXXXX-prepare.svg'
command = 'inkscape ' + file + ' --actions="select-all;object-unlink-clones;object-to-path" -o ' + tempfile
p = Popen(command, shell=True, stdout=PIPE, stderr=PIPE)
(out, err) = p.communicate()
print(p.returncode)
```

If it matters, this is under wayland.

**Comment by mgmax** [comment]
Reason:

Some older Inkscape versions have trouble calling themselves from an extension (Inkscape -> extension -> Inkscape).

Workaround:

https://github.com/t-oster/VisiCut/blob/5c2e8adc3ee2f4f7e130e22c22352fec82529529/tools/inkscape_extension/visicut_export.py#L45-L49

Good solution:

The Inkcut extension should use the `inkex.command.inkscape()` function for calling Inkscape so that it doesn't need such workarounds. This will also handle other special cases.
https://inkscape-extensions-guide.readthedocs.io/en/latest/inkex-modules.html#inkex.command.inkscape
