### ISSUE TITLE
Support for rotated elliptical arcs

### ISSUE THREAD

**Issue by raboof** [inkcut/inkcut#45]
Non-rotated elliptical arcs are in #42, see also issue #37 

See also this svg from the [spec](https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands): 
[arcs.svg.txt](https://github.com/codelv/inkcut/files/1863091/arcs.svg.txt)

**Comment by goatchurchprime** [comment]
All curves are linearized before they go to the HPGL code, and Inkcut is using the functions  QtPainterPath to interpolate the points.  Therefore it can only handle curves that are expressed in Qt.  

https://srinikom.github.io/pyside-docs/PySide/QtSvg/QSvgWidget.html
https://srinikom.github.io/pyside-docs/PySide/QtGui/QPainterPath.html

Unfortunately the QtGui.QPainterPath.arcTo() function doesn't implement the full rotated ellipse arc from the SVG spec, eg `<path  d="m 0 50 a 60 10 45 0 1 0 70">` 

However, it can do rotated arcs if it is given as a transform, eg `<path d="m 0 50 a 60 10 0 0 1 0 70" transform = "rotate(-45 50 50)"/>`

Every SVG rotated ellipse could be converted into an equivalent transform(rotated) ellipse on loading -- if we can get the calculation right.  

It's probably about twelve lines of code with barely any change to the rest of the system, but it would take forever to debug and get right.  Might want to start with a place like here:  https://observablehq.com/@toja/ellipse-and-elliptical-arc-conversion




[rotatedarcs.zip](https://github.com/inkcut/inkcut/files/4008494/rotatedarcs.zip)

**Comment by goatchurchprime** [comment]
Given that the [QtPainterPath](https://srinikom.github.io/pyside-docs/PySide/QtGui/QPainterPath.html) object does not have an `arcTo()` function capable of expressing non-zero arc rotation SVG arcs, I decided to check out the how the function [QSvgWidget.load](https://srinikom.github.io/pyside-docs/PySide/QtSvg/QSvgWidget.html?highlight=qsvg#PySide.QtSvg.PySide.QtSvg.QSvgWidget.load) function in the Qt library handles the situation.  

With regards to handling SVG path objects, the **inkcut** function [QtSvgPath.parse()](https://github.com/inkcut/inkcut/blob/master/inkcut/core/svg.py#L350) is equivalent to the **Qt** function [parsePathDataFast()](https://github.com/radekp/qt/blob/master/src/svg/qsvghandler.cpp#L1503).  The latter handles the SVG-path "A" case by calling [pathArc()](https://github.com/radekp/qt/blob/master/src/svg/qsvghandler.cpp#L1423) which breaks the arc into pieces smaller than 90 degrees, and then calls [pathArcSegment()](https://github.com/radekp/qt/blob/master/src/svg/qsvghandler.cpp#L1364) where it is approximated by a single cubic spline.

This might be okay in computer graphics, but it's not good enough if we're supposed to be cutting shapes in the physical world where things may need to fit together (eg gear teeth).  

Given that the paths are all polygonized (linearized) on the fly at 1mm intervals when plotting the output to HPGL, it would be sensible to flatten (linearize) them on input so that what we see is what we get (in terms of the flatness).  It makes it really difficult to deal with if the flats are on the cut part but not on the screen graphics where you are more able to diagnose the problem and learn about changing the settings.

Now, Inkscape has a Flatten Beziers function under Extensions|Modify Path, which calls into [flatten.py](https://gitlab.com/inkscape/inkscape/blob/0.92.x/share/extensions/flatten.py) where d-string from the path object is first [approximated](https://gitlab.com/inkscape/inkscape/blob/0.92.x/share/extensions/cubicsuperpath.py#L44) into a list of cubic splines (as they are in the Qt svg load function) that are then [recursively subdivided](https://gitlab.com/inkscape/inkscape/blob/0.92.x/share/extensions/cspsubdiv.py) at the halfpoints until it achieves the flatness tolerance.  

This is not great either, and hopefully not the sort of sub-optimal inaccurate implementation that is used in a normal browser.

Uh oh.  Going through the source code for FireFox there is the function [ArcToBezier()](https://github.com/mozilla/gecko-dev/blob/ce02064d8afc8673cef83c92896ee873bd35e7ae/gfx/2d/PathHelpers.h#L124).  

I don't get the point: if it's always the case that every time you ask for an elliptical arc you're just getting a cubic spline, why have the elliptical arc in the SVG standard at all?

**Comment by goatchurchprime** [comment]
If this bugreport in Qt had been acted upon https://bugreports.qt.io/browse/QTBUG-70320 asking about exposing the parsePathDataFast() function into the QtPainterPath class then the whole of the  QtSvgPath.parse() inkcut function (and its shortcomings) would be made redundant.

**Comment by frmdstryr** [comment]
Thanks for all the work on this @goatchurchprime  and @raboof ! Please open a new issue if anything else is found.
